#include "startwindow.h"
#include "ui_startwindow.h"
#include "setprofile.h"

/*
 * Default constructor generated by QT.
 */
StartWindow::StartWindow(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::StartWindow)
{
    ui->setupUi(this);
    this->setWindowTitle("Roulette");
    this->move(800, 250);//window positioning
    setStyleSheet("StartWindow {background-color:green};");

}

StartWindow::~StartWindow()
{
    delete ui;
}



/*
 * This method takes no parameters.
 * Activates the form which will lead the player to a new game.
 * This method doesn't return anything
 */
void StartWindow::on_pushButton_new_clicked()
{
    setprof = new SetProfile();
    setprof->show();
}

/*
 * This method takes no parameters.
 * Activates the form which will take the player to the load account screen.
 * This method doesn't return anything
 */
void StartWindow::on_pushButton_load_clicked()
{
    load = new LoadGame();
    load->show();
}

/*
 * This method takes no parameters.
 * Closes the game.
 * This method doesn't return anything
 */
void StartWindow::on_pushButton_quit_clicked()
{
    QApplication::quit();
}

