/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *pushButton_1;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_spin;
    QPushButton *pushButton_10;
    QPushButton *pushButton_9;
    QPushButton *pushButton_11;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_12;
    QPushButton *pushButton_16;
    QPushButton *pushButton_15;
    QPushButton *pushButton_17;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_18;
    QPushButton *pushButton_22;
    QPushButton *pushButton_21;
    QPushButton *pushButton_23;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_24;
    QPushButton *pushButton_28;
    QPushButton *pushButton_27;
    QPushButton *pushButton_29;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_30;
    QPushButton *pushButton_34;
    QPushButton *pushButton_33;
    QPushButton *pushButton_35;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_36;
    QPushButton *pushButton_0;
    QPushButton *pushButton_1st;
    QPushButton *pushButton_2nd;
    QPushButton *pushButton_3rd;
    QPushButton *pushButton_1_18;
    QPushButton *pushButton_even;
    QPushButton *redButton_red;
    QPushButton *pushButton_black;
    QPushButton *pushButton_odd;
    QPushButton *pushButton_19_36;
    QPushButton *pushButton_2to1_3;
    QPushButton *pushButton_2to1_2;
    QPushButton *pushButton_2to1_1;
    QPushButton *pushButton_1_plus_4;
    QPushButton *pushButton_2_plus_5;
    QPushButton *pushButton_1_plus_4_2_5;
    QPushButton *pushButton_2_plus_5_3_6;
    QPushButton *pushButton_7_plus_10_8_11;
    QPushButton *pushButton_26_plus_29_27_30;
    QPushButton *pushButton_1_plus_2;
    QPushButton *pushButton_4_plus_5;
    QPushButton *pushButton_3_plus_6;
    QPushButton *pushButton_2_plus_3;
    QPushButton *pushButton_5_plus_6;
    QPushButton *pushButton_6_plus_9;
    QPushButton *pushButton_5_plus_8_6_9;
    QPushButton *pushButton_4_plus_7_5_8;
    QPushButton *pushButton_4_plus_7;
    QPushButton *pushButton_5_plus_8;
    QPushButton *pushButton_7_plus_8;
    QPushButton *pushButton_23_plus_26_24_27;
    QPushButton *pushButton_19_plus_22;
    QPushButton *pushButton_20_plus_23;
    QPushButton *pushButton_13_plus_16;
    QPushButton *pushButton_32_plus_35_33_36;
    QPushButton *pushButton_22_plus_25_23_26;
    QPushButton *pushButton_18_plus_21;
    QPushButton *pushButton_21_plus_24;
    QPushButton *pushButton_14_plus_17;
    QPushButton *pushButton_29_plus_32_30_33;
    QPushButton *pushButton_29_plus_32;
    QPushButton *pushButton_31_plus_34;
    QPushButton *pushButton_23_plus_26;
    QPushButton *pushButton_28_plus_31;
    QPushButton *pushButton_32_plus_35;
    QPushButton *pushButton_30_plus_33;
    QPushButton *pushButton_27_plus_30;
    QPushButton *pushButton_33_plus_36;
    QPushButton *pushButton_25_plus_28;
    QPushButton *pushButton_25_plus_28_26_29;
    QPushButton *pushButton_22_plus_25;
    QPushButton *pushButton_26_plus_29;
    QPushButton *pushButton_24_plus_27;
    QPushButton *pushButton_31_plus_34_32_35;
    QPushButton *pushButton_19_plus_22_20_23;
    QPushButton *pushButton_16_plus_19;
    QPushButton *pushButton_17_plus_20;
    QPushButton *pushButton_15_plus_18;
    QPushButton *pushButton_28_plus_31_29_32;
    QPushButton *pushButton_16_plus_19_17_20;
    QPushButton *pushButton_7_plus_10;
    QPushButton *pushButton_10_plus_13;
    QPushButton *pushButton_8_plus_11;
    QPushButton *pushButton_17_plus_20_18_21;
    QPushButton *pushButton_13_plus_16_14_17;
    QPushButton *pushButton_11_plus_14;
    QPushButton *pushButton_12_plus_15;
    QPushButton *pushButton_9_plus_12;
    QPushButton *pushButton_20_plus_23_21_24;
    QPushButton *pushButton_14_plus_15;
    QPushButton *pushButton_14_plus_17_15_18;
    QPushButton *pushButton_11_plus_14_12_15;
    QPushButton *pushButton_11_plus_12;
    QPushButton *pushButton_8_plus_11_9_12;
    QPushButton *pushButton_8_plus_9;
    QPushButton *pushButton_10_plus_13_11_14;
    QPushButton *pushButton_10_plus_11;
    QPushButton *pushButton_13_plus_14;
    QPushButton *pushButton_17_plus_18;
    QPushButton *pushButton_16_plus_17;
    QPushButton *pushButton_20_plus_21;
    QPushButton *pushButton_23_plus_24;
    QPushButton *pushButton_19_plus_20;
    QPushButton *pushButton_22_plus_23;
    QPushButton *pushButton_26_plus_27;
    QPushButton *pushButton_25_plus_26;
    QPushButton *pushButton_29_plus_30;
    QPushButton *pushButton_28_plus_29;
    QPushButton *pushButton_35_plus_36;
    QPushButton *pushButton_34_plus_35;
    QPushButton *pushButton_31_plus_32;
    QPushButton *pushButton_32_plus_33;
    QPushButton *Bet_button1;
    QPushButton *Bet_button2;
    QPushButton *Bet_button3;
    QPushButton *Bet_button4;
    QPushButton *Clear_Button;
    QLabel *label_gif;
    QPushButton *Bet_button5;
    QPushButton *Bet_button6;
    QPushButton *pushButton_street_6;
    QPushButton *pushButton_street_10;
    QPushButton *pushButton_line_2;
    QPushButton *pushButton_street_3;
    QPushButton *pushButton_line_3;
    QPushButton *pushButton_line_5;
    QPushButton *pushButton_line_11;
    QPushButton *pushButton_street_2;
    QPushButton *pushButton_line_6;
    QPushButton *pushButton_street_5;
    QPushButton *pushButton_street_9;
    QPushButton *pushButton_line_8;
    QPushButton *pushButton_line_4;
    QPushButton *pushButton_street_1;
    QPushButton *pushButton_line_7;
    QPushButton *pushButton_line_10;
    QPushButton *pushButton_line_9;
    QPushButton *pushButton_line_1;
    QPushButton *pushButton_street_7;
    QPushButton *pushButton_street_8;
    QPushButton *pushButton_street_12;
    QPushButton *pushButton_street_11;
    QPushButton *pushButton_street_4;
    QPushButton *pushButton_3rd_row;
    QPushButton *pushButton_2nd_row;
    QPushButton *pushButton_1st_row;
    QLabel *label;
    QLabel *label_2;
    QLabel *nameShowcase;
    QLabel *creditsShowcase;
    QMenuBar *menuBar;
    QMenu *menuRoullet;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1108, 656);
        MainWindow->setStyleSheet(QStringLiteral(""));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        pushButton_1 = new QPushButton(centralWidget);
        pushButton_1->setObjectName(QStringLiteral("pushButton_1"));
        pushButton_1->setGeometry(QRect(100, 250, 61, 61));
        pushButton_1->setMinimumSize(QSize(0, 0));
        pushButton_1->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_1->setAutoDefault(true);
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(100, 183, 61, 61));
        pushButton_2->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_2->setAutoDefault(true);
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(100, 116, 61, 61));
        pushButton_3->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_3->setAutoDefault(true);
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(167, 250, 61, 61));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_4->setAutoDefault(true);
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(167, 183, 61, 61));
        pushButton_5->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_5->setAutoDefault(true);
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(167, 116, 61, 61));
        pushButton_6->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_6->setAutoDefault(true);
        pushButton_spin = new QPushButton(centralWidget);
        pushButton_spin->setObjectName(QStringLiteral("pushButton_spin"));
        pushButton_spin->setGeometry(QRect(365, 450, 268, 41));
        pushButton_spin->setStyleSheet(QLatin1String("\n"
"color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_spin->setAutoDefault(true);
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(301, 249, 61, 61));
        pushButton_10->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_10->setAutoDefault(true);
        pushButton_9 = new QPushButton(centralWidget);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(234, 115, 61, 61));
        pushButton_9->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_9->setAutoDefault(true);
        pushButton_11 = new QPushButton(centralWidget);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(301, 182, 61, 61));
        pushButton_11->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_11->setAutoDefault(true);
        pushButton_7 = new QPushButton(centralWidget);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(234, 249, 61, 61));
        pushButton_7->setMinimumSize(QSize(0, 0));
        pushButton_7->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_7->setAutoDefault(true);
        pushButton_8 = new QPushButton(centralWidget);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(234, 182, 61, 61));
        pushButton_8->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_8->setAutoDefault(true);
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(301, 115, 61, 61));
        pushButton_12->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_12->setAutoDefault(true);
        pushButton_16 = new QPushButton(centralWidget);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(436, 248, 61, 61));
        pushButton_16->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_16->setAutoDefault(true);
        pushButton_15 = new QPushButton(centralWidget);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(368, 114, 61, 61));
        pushButton_15->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_15->setAutoDefault(true);
        pushButton_17 = new QPushButton(centralWidget);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(435, 181, 61, 61));
        pushButton_17->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_17->setAutoDefault(true);
        pushButton_13 = new QPushButton(centralWidget);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(369, 248, 61, 61));
        pushButton_13->setMinimumSize(QSize(0, 0));
        pushButton_13->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_13->setAutoDefault(true);
        pushButton_14 = new QPushButton(centralWidget);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(369, 181, 61, 61));
        pushButton_14->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_14->setAutoDefault(true);
        pushButton_18 = new QPushButton(centralWidget);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(435, 114, 61, 61));
        pushButton_18->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_18->setAutoDefault(true);
        pushButton_22 = new QPushButton(centralWidget);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(570, 248, 61, 61));
        pushButton_22->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_22->setAutoDefault(true);
        pushButton_21 = new QPushButton(centralWidget);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(502, 114, 61, 61));
        pushButton_21->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_21->setAutoDefault(true);
        pushButton_23 = new QPushButton(centralWidget);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(570, 181, 61, 61));
        pushButton_23->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_23->setAutoDefault(true);
        pushButton_19 = new QPushButton(centralWidget);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(503, 248, 61, 61));
        pushButton_19->setMinimumSize(QSize(0, 0));
        pushButton_19->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_19->setAutoDefault(true);
        pushButton_20 = new QPushButton(centralWidget);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(503, 181, 61, 61));
        pushButton_20->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_20->setAutoDefault(true);
        pushButton_24 = new QPushButton(centralWidget);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(569, 114, 61, 61));
        pushButton_24->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_24->setAutoDefault(true);
        pushButton_28 = new QPushButton(centralWidget);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(704, 248, 61, 61));
        pushButton_28->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_28->setAutoDefault(true);
        pushButton_27 = new QPushButton(centralWidget);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(636, 114, 61, 61));
        pushButton_27->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_27->setAutoDefault(true);
        pushButton_29 = new QPushButton(centralWidget);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(704, 181, 61, 61));
        pushButton_29->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_29->setAutoDefault(true);
        pushButton_25 = new QPushButton(centralWidget);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(637, 248, 61, 61));
        pushButton_25->setMinimumSize(QSize(0, 0));
        pushButton_25->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_25->setAutoDefault(true);
        pushButton_26 = new QPushButton(centralWidget);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(637, 181, 61, 61));
        pushButton_26->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_26->setAutoDefault(true);
        pushButton_30 = new QPushButton(centralWidget);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(703, 114, 61, 61));
        pushButton_30->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_30->setAutoDefault(true);
        pushButton_34 = new QPushButton(centralWidget);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(838, 248, 61, 61));
        pushButton_34->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_34->setAutoDefault(true);
        pushButton_33 = new QPushButton(centralWidget);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(770, 114, 61, 61));
        pushButton_33->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_33->setAutoDefault(true);
        pushButton_35 = new QPushButton(centralWidget);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(838, 181, 61, 61));
        pushButton_35->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_35->setAutoDefault(true);
        pushButton_31 = new QPushButton(centralWidget);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(771, 248, 61, 61));
        pushButton_31->setMinimumSize(QSize(0, 0));
        pushButton_31->setStyleSheet(QStringLiteral("background-color: black; color:white; border-radius: 5px"));
        pushButton_31->setAutoDefault(true);
        pushButton_32 = new QPushButton(centralWidget);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(771, 181, 61, 61));
        pushButton_32->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_32->setAutoDefault(true);
        pushButton_36 = new QPushButton(centralWidget);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(837, 114, 61, 61));
        pushButton_36->setStyleSheet(QStringLiteral("background-color: red; color: white;border-radius: 5px;"));
        pushButton_36->setAutoDefault(true);
        pushButton_0 = new QPushButton(centralWidget);
        pushButton_0->setObjectName(QStringLiteral("pushButton_0"));
        pushButton_0->setGeometry(QRect(28, 115, 71, 199));
        pushButton_0->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_0->setAutoDefault(true);
        pushButton_1st = new QPushButton(centralWidget);
        pushButton_1st->setObjectName(QStringLiteral("pushButton_1st"));
        pushButton_1st->setGeometry(QRect(99, 320, 266, 41));
        pushButton_1st->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_1st->setAutoDefault(true);
        pushButton_2nd = new QPushButton(centralWidget);
        pushButton_2nd->setObjectName(QStringLiteral("pushButton_2nd"));
        pushButton_2nd->setGeometry(QRect(365, 320, 268, 41));
        pushButton_2nd->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_2nd->setAutoDefault(true);
        pushButton_3rd = new QPushButton(centralWidget);
        pushButton_3rd->setObjectName(QStringLiteral("pushButton_3rd"));
        pushButton_3rd->setGeometry(QRect(633, 320, 268, 41));
        pushButton_3rd->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_3rd->setAutoDefault(true);
        pushButton_1_18 = new QPushButton(centralWidget);
        pushButton_1_18->setObjectName(QStringLiteral("pushButton_1_18"));
        pushButton_1_18->setGeometry(QRect(99, 360, 133, 41));
        pushButton_1_18->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
""));
        pushButton_1_18->setAutoDefault(true);
        pushButton_even = new QPushButton(centralWidget);
        pushButton_even->setObjectName(QStringLiteral("pushButton_even"));
        pushButton_even->setGeometry(QRect(232, 360, 133, 41));
        pushButton_even->setStyleSheet(QLatin1String("color:yellow;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_even->setAutoDefault(true);
        redButton_red = new QPushButton(centralWidget);
        redButton_red->setObjectName(QStringLiteral("redButton_red"));
        redButton_red->setGeometry(QRect(365, 360, 134, 41));
        redButton_red->setStyleSheet(QLatin1String("background-color: red; \n"
"color: white;\n"
"border-radius: 5px;"));
        redButton_red->setAutoDefault(true);
        pushButton_black = new QPushButton(centralWidget);
        pushButton_black->setObjectName(QStringLiteral("pushButton_black"));
        pushButton_black->setEnabled(true);
        pushButton_black->setGeometry(QRect(499, 360, 134, 41));
        pushButton_black->setAutoFillBackground(false);
        pushButton_black->setStyleSheet(QLatin1String("background-color: black; \n"
"color: white;\n"
"border-radius: 5px;"));
        pushButton_black->setAutoDefault(true);
        pushButton_odd = new QPushButton(centralWidget);
        pushButton_odd->setObjectName(QStringLiteral("pushButton_odd"));
        pushButton_odd->setGeometry(QRect(634, 360, 134, 41));
        pushButton_odd->setStyleSheet(QLatin1String("color:yellow;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_odd->setAutoDefault(true);
        pushButton_19_36 = new QPushButton(centralWidget);
        pushButton_19_36->setObjectName(QStringLiteral("pushButton_19_36"));
        pushButton_19_36->setGeometry(QRect(768, 360, 134, 41));
        pushButton_19_36->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_19_36->setAutoDefault(true);
        pushButton_2to1_3 = new QPushButton(centralWidget);
        pushButton_2to1_3->setObjectName(QStringLiteral("pushButton_2to1_3"));
        pushButton_2to1_3->setGeometry(QRect(899, 248, 51, 61));
        pushButton_2to1_3->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_2to1_3->setAutoDefault(true);
        pushButton_2to1_2 = new QPushButton(centralWidget);
        pushButton_2to1_2->setObjectName(QStringLiteral("pushButton_2to1_2"));
        pushButton_2to1_2->setGeometry(QRect(899, 181, 51, 61));
        pushButton_2to1_2->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_2to1_2->setAutoDefault(true);
        pushButton_2to1_1 = new QPushButton(centralWidget);
        pushButton_2to1_1->setObjectName(QStringLiteral("pushButton_2to1_1"));
        pushButton_2to1_1->setGeometry(QRect(898, 114, 51, 61));
        pushButton_2to1_1->setStyleSheet(QLatin1String("color:white;\n"
"border-color:white;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"border-radius: 5px;"));
        pushButton_2to1_1->setAutoDefault(true);
        pushButton_1_plus_4 = new QPushButton(centralWidget);
        pushButton_1_plus_4->setObjectName(QStringLiteral("pushButton_1_plus_4"));
        pushButton_1_plus_4->setGeometry(QRect(160, 250, 8, 61));
        pushButton_1_plus_4->setStyleSheet(QStringLiteral(""));
        pushButton_1_plus_4->setAutoDefault(true);
        pushButton_2_plus_5 = new QPushButton(centralWidget);
        pushButton_2_plus_5->setObjectName(QStringLiteral("pushButton_2_plus_5"));
        pushButton_2_plus_5->setGeometry(QRect(160, 181, 8, 61));
        pushButton_2_plus_5->setStyleSheet(QStringLiteral(""));
        pushButton_2_plus_5->setAutoDefault(true);
        pushButton_1_plus_4_2_5 = new QPushButton(centralWidget);
        pushButton_1_plus_4_2_5->setObjectName(QStringLiteral("pushButton_1_plus_4_2_5"));
        pushButton_1_plus_4_2_5->setGeometry(QRect(158, 240, 12, 12));
        pushButton_1_plus_4_2_5->setStyleSheet(QStringLiteral(""));
        pushButton_1_plus_4_2_5->setAutoDefault(true);
        pushButton_2_plus_5_3_6 = new QPushButton(centralWidget);
        pushButton_2_plus_5_3_6->setObjectName(QStringLiteral("pushButton_2_plus_5_3_6"));
        pushButton_2_plus_5_3_6->setGeometry(QRect(158, 173, 12, 12));
        pushButton_2_plus_5_3_6->setStyleSheet(QStringLiteral(""));
        pushButton_2_plus_5_3_6->setAutoDefault(true);
        pushButton_7_plus_10_8_11 = new QPushButton(centralWidget);
        pushButton_7_plus_10_8_11->setObjectName(QStringLiteral("pushButton_7_plus_10_8_11"));
        pushButton_7_plus_10_8_11->setGeometry(QRect(292, 240, 12, 12));
        pushButton_7_plus_10_8_11->setStyleSheet(QStringLiteral(""));
        pushButton_7_plus_10_8_11->setAutoDefault(true);
        pushButton_26_plus_29_27_30 = new QPushButton(centralWidget);
        pushButton_26_plus_29_27_30->setObjectName(QStringLiteral("pushButton_26_plus_29_27_30"));
        pushButton_26_plus_29_27_30->setGeometry(QRect(695, 172, 12, 12));
        pushButton_26_plus_29_27_30->setStyleSheet(QStringLiteral(""));
        pushButton_26_plus_29_27_30->setAutoDefault(true);
        pushButton_1_plus_2 = new QPushButton(centralWidget);
        pushButton_1_plus_2->setObjectName(QStringLiteral("pushButton_1_plus_2"));
        pushButton_1_plus_2->setGeometry(QRect(100, 243, 61, 8));
        pushButton_1_plus_2->setStyleSheet(QStringLiteral(""));
        pushButton_1_plus_2->setAutoDefault(true);
        pushButton_4_plus_5 = new QPushButton(centralWidget);
        pushButton_4_plus_5->setObjectName(QStringLiteral("pushButton_4_plus_5"));
        pushButton_4_plus_5->setGeometry(QRect(167, 243, 61, 8));
        pushButton_4_plus_5->setStyleSheet(QStringLiteral(""));
        pushButton_4_plus_5->setAutoDefault(true);
        pushButton_3_plus_6 = new QPushButton(centralWidget);
        pushButton_3_plus_6->setObjectName(QStringLiteral("pushButton_3_plus_6"));
        pushButton_3_plus_6->setGeometry(QRect(160, 114, 8, 61));
        pushButton_3_plus_6->setStyleSheet(QStringLiteral(""));
        pushButton_3_plus_6->setAutoDefault(true);
        pushButton_2_plus_3 = new QPushButton(centralWidget);
        pushButton_2_plus_3->setObjectName(QStringLiteral("pushButton_2_plus_3"));
        pushButton_2_plus_3->setGeometry(QRect(100, 176, 61, 8));
        pushButton_2_plus_3->setAutoFillBackground(false);
        pushButton_2_plus_3->setStyleSheet(QStringLiteral(""));
        pushButton_2_plus_3->setAutoDefault(true);
        pushButton_5_plus_6 = new QPushButton(centralWidget);
        pushButton_5_plus_6->setObjectName(QStringLiteral("pushButton_5_plus_6"));
        pushButton_5_plus_6->setGeometry(QRect(167, 176, 61, 8));
        pushButton_5_plus_6->setStyleSheet(QStringLiteral(""));
        pushButton_5_plus_6->setAutoDefault(true);
        pushButton_6_plus_9 = new QPushButton(centralWidget);
        pushButton_6_plus_9->setObjectName(QStringLiteral("pushButton_6_plus_9"));
        pushButton_6_plus_9->setGeometry(QRect(227, 114, 8, 61));
        pushButton_6_plus_9->setStyleSheet(QStringLiteral(""));
        pushButton_6_plus_9->setAutoDefault(true);
        pushButton_5_plus_8_6_9 = new QPushButton(centralWidget);
        pushButton_5_plus_8_6_9->setObjectName(QStringLiteral("pushButton_5_plus_8_6_9"));
        pushButton_5_plus_8_6_9->setGeometry(QRect(225, 172, 12, 12));
        pushButton_5_plus_8_6_9->setStyleSheet(QStringLiteral(""));
        pushButton_5_plus_8_6_9->setAutoDefault(true);
        pushButton_4_plus_7_5_8 = new QPushButton(centralWidget);
        pushButton_4_plus_7_5_8->setObjectName(QStringLiteral("pushButton_4_plus_7_5_8"));
        pushButton_4_plus_7_5_8->setGeometry(QRect(225, 240, 12, 12));
        pushButton_4_plus_7_5_8->setStyleSheet(QStringLiteral(""));
        pushButton_4_plus_7_5_8->setAutoDefault(true);
        pushButton_4_plus_7 = new QPushButton(centralWidget);
        pushButton_4_plus_7->setObjectName(QStringLiteral("pushButton_4_plus_7"));
        pushButton_4_plus_7->setGeometry(QRect(227, 250, 8, 61));
        pushButton_4_plus_7->setStyleSheet(QStringLiteral(""));
        pushButton_4_plus_7->setAutoDefault(true);
        pushButton_5_plus_8 = new QPushButton(centralWidget);
        pushButton_5_plus_8->setObjectName(QStringLiteral("pushButton_5_plus_8"));
        pushButton_5_plus_8->setGeometry(QRect(227, 181, 8, 61));
        pushButton_5_plus_8->setStyleSheet(QStringLiteral(""));
        pushButton_5_plus_8->setAutoDefault(true);
        pushButton_7_plus_8 = new QPushButton(centralWidget);
        pushButton_7_plus_8->setObjectName(QStringLiteral("pushButton_7_plus_8"));
        pushButton_7_plus_8->setGeometry(QRect(234, 242, 61, 8));
        pushButton_7_plus_8->setStyleSheet(QStringLiteral(""));
        pushButton_7_plus_8->setAutoDefault(true);
        pushButton_23_plus_26_24_27 = new QPushButton(centralWidget);
        pushButton_23_plus_26_24_27->setObjectName(QStringLiteral("pushButton_23_plus_26_24_27"));
        pushButton_23_plus_26_24_27->setGeometry(QRect(628, 172, 12, 12));
        pushButton_23_plus_26_24_27->setStyleSheet(QStringLiteral(""));
        pushButton_23_plus_26_24_27->setAutoDefault(true);
        pushButton_19_plus_22 = new QPushButton(centralWidget);
        pushButton_19_plus_22->setObjectName(QStringLiteral("pushButton_19_plus_22"));
        pushButton_19_plus_22->setGeometry(QRect(563, 249, 8, 61));
        pushButton_19_plus_22->setStyleSheet(QStringLiteral(""));
        pushButton_19_plus_22->setAutoDefault(true);
        pushButton_20_plus_23 = new QPushButton(centralWidget);
        pushButton_20_plus_23->setObjectName(QStringLiteral("pushButton_20_plus_23"));
        pushButton_20_plus_23->setGeometry(QRect(563, 182, 8, 61));
        pushButton_20_plus_23->setStyleSheet(QStringLiteral(""));
        pushButton_20_plus_23->setAutoDefault(true);
        pushButton_13_plus_16 = new QPushButton(centralWidget);
        pushButton_13_plus_16->setObjectName(QStringLiteral("pushButton_13_plus_16"));
        pushButton_13_plus_16->setGeometry(QRect(429, 249, 8, 61));
        pushButton_13_plus_16->setStyleSheet(QStringLiteral(""));
        pushButton_13_plus_16->setAutoDefault(true);
        pushButton_32_plus_35_33_36 = new QPushButton(centralWidget);
        pushButton_32_plus_35_33_36->setObjectName(QStringLiteral("pushButton_32_plus_35_33_36"));
        pushButton_32_plus_35_33_36->setGeometry(QRect(829, 172, 12, 12));
        pushButton_32_plus_35_33_36->setStyleSheet(QStringLiteral(""));
        pushButton_32_plus_35_33_36->setAutoDefault(true);
        pushButton_22_plus_25_23_26 = new QPushButton(centralWidget);
        pushButton_22_plus_25_23_26->setObjectName(QStringLiteral("pushButton_22_plus_25_23_26"));
        pushButton_22_plus_25_23_26->setGeometry(QRect(628, 239, 12, 12));
        pushButton_22_plus_25_23_26->setStyleSheet(QStringLiteral(""));
        pushButton_22_plus_25_23_26->setAutoDefault(true);
        pushButton_18_plus_21 = new QPushButton(centralWidget);
        pushButton_18_plus_21->setObjectName(QStringLiteral("pushButton_18_plus_21"));
        pushButton_18_plus_21->setGeometry(QRect(495, 113, 8, 61));
        pushButton_18_plus_21->setStyleSheet(QStringLiteral(""));
        pushButton_18_plus_21->setAutoDefault(true);
        pushButton_21_plus_24 = new QPushButton(centralWidget);
        pushButton_21_plus_24->setObjectName(QStringLiteral("pushButton_21_plus_24"));
        pushButton_21_plus_24->setGeometry(QRect(562, 113, 8, 61));
        pushButton_21_plus_24->setStyleSheet(QStringLiteral(""));
        pushButton_21_plus_24->setAutoDefault(true);
        pushButton_14_plus_17 = new QPushButton(centralWidget);
        pushButton_14_plus_17->setObjectName(QStringLiteral("pushButton_14_plus_17"));
        pushButton_14_plus_17->setGeometry(QRect(428, 181, 8, 61));
        pushButton_14_plus_17->setStyleSheet(QStringLiteral("background:white;"));
        pushButton_14_plus_17->setAutoDefault(true);
        pushButton_29_plus_32_30_33 = new QPushButton(centralWidget);
        pushButton_29_plus_32_30_33->setObjectName(QStringLiteral("pushButton_29_plus_32_30_33"));
        pushButton_29_plus_32_30_33->setGeometry(QRect(762, 172, 12, 12));
        pushButton_29_plus_32_30_33->setStyleSheet(QStringLiteral(""));
        pushButton_29_plus_32_30_33->setAutoDefault(true);
        pushButton_29_plus_32 = new QPushButton(centralWidget);
        pushButton_29_plus_32->setObjectName(QStringLiteral("pushButton_29_plus_32"));
        pushButton_29_plus_32->setGeometry(QRect(764, 181, 8, 61));
        pushButton_29_plus_32->setStyleSheet(QStringLiteral(""));
        pushButton_29_plus_32->setAutoDefault(true);
        pushButton_31_plus_34 = new QPushButton(centralWidget);
        pushButton_31_plus_34->setObjectName(QStringLiteral("pushButton_31_plus_34"));
        pushButton_31_plus_34->setGeometry(QRect(831, 249, 8, 61));
        pushButton_31_plus_34->setStyleSheet(QStringLiteral(""));
        pushButton_31_plus_34->setAutoDefault(true);
        pushButton_23_plus_26 = new QPushButton(centralWidget);
        pushButton_23_plus_26->setObjectName(QStringLiteral("pushButton_23_plus_26"));
        pushButton_23_plus_26->setGeometry(QRect(630, 181, 8, 61));
        pushButton_23_plus_26->setStyleSheet(QStringLiteral(""));
        pushButton_23_plus_26->setAutoDefault(true);
        pushButton_28_plus_31 = new QPushButton(centralWidget);
        pushButton_28_plus_31->setObjectName(QStringLiteral("pushButton_28_plus_31"));
        pushButton_28_plus_31->setGeometry(QRect(764, 249, 8, 61));
        pushButton_28_plus_31->setStyleSheet(QStringLiteral(""));
        pushButton_28_plus_31->setAutoDefault(true);
        pushButton_32_plus_35 = new QPushButton(centralWidget);
        pushButton_32_plus_35->setObjectName(QStringLiteral("pushButton_32_plus_35"));
        pushButton_32_plus_35->setGeometry(QRect(831, 181, 8, 61));
        pushButton_32_plus_35->setStyleSheet(QStringLiteral(""));
        pushButton_32_plus_35->setAutoDefault(true);
        pushButton_30_plus_33 = new QPushButton(centralWidget);
        pushButton_30_plus_33->setObjectName(QStringLiteral("pushButton_30_plus_33"));
        pushButton_30_plus_33->setGeometry(QRect(763, 113, 8, 61));
        pushButton_30_plus_33->setStyleSheet(QStringLiteral(""));
        pushButton_30_plus_33->setAutoDefault(true);
        pushButton_27_plus_30 = new QPushButton(centralWidget);
        pushButton_27_plus_30->setObjectName(QStringLiteral("pushButton_27_plus_30"));
        pushButton_27_plus_30->setGeometry(QRect(696, 113, 8, 61));
        pushButton_27_plus_30->setStyleSheet(QStringLiteral(""));
        pushButton_27_plus_30->setAutoDefault(true);
        pushButton_33_plus_36 = new QPushButton(centralWidget);
        pushButton_33_plus_36->setObjectName(QStringLiteral("pushButton_33_plus_36"));
        pushButton_33_plus_36->setGeometry(QRect(830, 113, 8, 61));
        pushButton_33_plus_36->setStyleSheet(QStringLiteral(""));
        pushButton_33_plus_36->setAutoDefault(true);
        pushButton_25_plus_28 = new QPushButton(centralWidget);
        pushButton_25_plus_28->setObjectName(QStringLiteral("pushButton_25_plus_28"));
        pushButton_25_plus_28->setGeometry(QRect(697, 249, 8, 61));
        pushButton_25_plus_28->setStyleSheet(QStringLiteral(""));
        pushButton_25_plus_28->setAutoDefault(true);
        pushButton_25_plus_28_26_29 = new QPushButton(centralWidget);
        pushButton_25_plus_28_26_29->setObjectName(QStringLiteral("pushButton_25_plus_28_26_29"));
        pushButton_25_plus_28_26_29->setGeometry(QRect(695, 239, 12, 12));
        pushButton_25_plus_28_26_29->setStyleSheet(QStringLiteral(""));
        pushButton_25_plus_28_26_29->setAutoDefault(true);
        pushButton_22_plus_25 = new QPushButton(centralWidget);
        pushButton_22_plus_25->setObjectName(QStringLiteral("pushButton_22_plus_25"));
        pushButton_22_plus_25->setGeometry(QRect(630, 248, 8, 61));
        pushButton_22_plus_25->setStyleSheet(QStringLiteral(""));
        pushButton_22_plus_25->setAutoDefault(true);
        pushButton_26_plus_29 = new QPushButton(centralWidget);
        pushButton_26_plus_29->setObjectName(QStringLiteral("pushButton_26_plus_29"));
        pushButton_26_plus_29->setGeometry(QRect(697, 181, 8, 61));
        pushButton_26_plus_29->setStyleSheet(QStringLiteral(""));
        pushButton_26_plus_29->setAutoDefault(true);
        pushButton_24_plus_27 = new QPushButton(centralWidget);
        pushButton_24_plus_27->setObjectName(QStringLiteral("pushButton_24_plus_27"));
        pushButton_24_plus_27->setGeometry(QRect(629, 113, 8, 61));
        pushButton_24_plus_27->setStyleSheet(QStringLiteral(""));
        pushButton_24_plus_27->setAutoDefault(true);
        pushButton_31_plus_34_32_35 = new QPushButton(centralWidget);
        pushButton_31_plus_34_32_35->setObjectName(QStringLiteral("pushButton_31_plus_34_32_35"));
        pushButton_31_plus_34_32_35->setGeometry(QRect(829, 239, 12, 12));
        pushButton_31_plus_34_32_35->setStyleSheet(QStringLiteral(""));
        pushButton_31_plus_34_32_35->setAutoDefault(true);
        pushButton_19_plus_22_20_23 = new QPushButton(centralWidget);
        pushButton_19_plus_22_20_23->setObjectName(QStringLiteral("pushButton_19_plus_22_20_23"));
        pushButton_19_plus_22_20_23->setGeometry(QRect(561, 239, 12, 12));
        pushButton_19_plus_22_20_23->setStyleSheet(QStringLiteral(""));
        pushButton_19_plus_22_20_23->setAutoDefault(true);
        pushButton_16_plus_19 = new QPushButton(centralWidget);
        pushButton_16_plus_19->setObjectName(QStringLiteral("pushButton_16_plus_19"));
        pushButton_16_plus_19->setGeometry(QRect(496, 248, 8, 61));
        pushButton_16_plus_19->setStyleSheet(QStringLiteral(""));
        pushButton_16_plus_19->setAutoDefault(true);
        pushButton_17_plus_20 = new QPushButton(centralWidget);
        pushButton_17_plus_20->setObjectName(QStringLiteral("pushButton_17_plus_20"));
        pushButton_17_plus_20->setGeometry(QRect(496, 182, 8, 61));
        pushButton_17_plus_20->setStyleSheet(QStringLiteral(""));
        pushButton_17_plus_20->setAutoDefault(true);
        pushButton_15_plus_18 = new QPushButton(centralWidget);
        pushButton_15_plus_18->setObjectName(QStringLiteral("pushButton_15_plus_18"));
        pushButton_15_plus_18->setGeometry(QRect(428, 114, 8, 61));
        pushButton_15_plus_18->setStyleSheet(QStringLiteral(""));
        pushButton_15_plus_18->setAutoDefault(true);
        pushButton_28_plus_31_29_32 = new QPushButton(centralWidget);
        pushButton_28_plus_31_29_32->setObjectName(QStringLiteral("pushButton_28_plus_31_29_32"));
        pushButton_28_plus_31_29_32->setGeometry(QRect(762, 239, 12, 12));
        pushButton_28_plus_31_29_32->setStyleSheet(QStringLiteral(""));
        pushButton_28_plus_31_29_32->setAutoDefault(true);
        pushButton_16_plus_19_17_20 = new QPushButton(centralWidget);
        pushButton_16_plus_19_17_20->setObjectName(QStringLiteral("pushButton_16_plus_19_17_20"));
        pushButton_16_plus_19_17_20->setGeometry(QRect(493, 239, 12, 12));
        pushButton_16_plus_19_17_20->setStyleSheet(QStringLiteral(""));
        pushButton_16_plus_19_17_20->setAutoDefault(true);
        pushButton_7_plus_10 = new QPushButton(centralWidget);
        pushButton_7_plus_10->setObjectName(QStringLiteral("pushButton_7_plus_10"));
        pushButton_7_plus_10->setGeometry(QRect(294, 250, 8, 61));
        pushButton_7_plus_10->setStyleSheet(QStringLiteral(""));
        pushButton_7_plus_10->setAutoDefault(true);
        pushButton_10_plus_13 = new QPushButton(centralWidget);
        pushButton_10_plus_13->setObjectName(QStringLiteral("pushButton_10_plus_13"));
        pushButton_10_plus_13->setGeometry(QRect(362, 250, 8, 61));
        pushButton_10_plus_13->setStyleSheet(QStringLiteral(""));
        pushButton_10_plus_13->setAutoDefault(true);
        pushButton_8_plus_11 = new QPushButton(centralWidget);
        pushButton_8_plus_11->setObjectName(QStringLiteral("pushButton_8_plus_11"));
        pushButton_8_plus_11->setGeometry(QRect(294, 182, 8, 61));
        pushButton_8_plus_11->setStyleSheet(QStringLiteral(""));
        pushButton_8_plus_11->setAutoDefault(true);
        pushButton_17_plus_20_18_21 = new QPushButton(centralWidget);
        pushButton_17_plus_20_18_21->setObjectName(QStringLiteral("pushButton_17_plus_20_18_21"));
        pushButton_17_plus_20_18_21->setGeometry(QRect(493, 172, 12, 12));
        pushButton_17_plus_20_18_21->setStyleSheet(QStringLiteral(""));
        pushButton_17_plus_20_18_21->setAutoDefault(true);
        pushButton_13_plus_16_14_17 = new QPushButton(centralWidget);
        pushButton_13_plus_16_14_17->setObjectName(QStringLiteral("pushButton_13_plus_16_14_17"));
        pushButton_13_plus_16_14_17->setGeometry(QRect(426, 239, 12, 12));
        pushButton_13_plus_16_14_17->setStyleSheet(QStringLiteral(""));
        pushButton_13_plus_16_14_17->setAutoDefault(true);
        pushButton_11_plus_14 = new QPushButton(centralWidget);
        pushButton_11_plus_14->setObjectName(QStringLiteral("pushButton_11_plus_14"));
        pushButton_11_plus_14->setGeometry(QRect(362, 182, 8, 61));
        pushButton_11_plus_14->setStyleSheet(QStringLiteral(""));
        pushButton_11_plus_14->setAutoDefault(true);
        pushButton_12_plus_15 = new QPushButton(centralWidget);
        pushButton_12_plus_15->setObjectName(QStringLiteral("pushButton_12_plus_15"));
        pushButton_12_plus_15->setGeometry(QRect(361, 114, 8, 61));
        pushButton_12_plus_15->setStyleSheet(QStringLiteral(""));
        pushButton_12_plus_15->setAutoDefault(true);
        pushButton_9_plus_12 = new QPushButton(centralWidget);
        pushButton_9_plus_12->setObjectName(QStringLiteral("pushButton_9_plus_12"));
        pushButton_9_plus_12->setGeometry(QRect(294, 115, 8, 61));
        pushButton_9_plus_12->setStyleSheet(QStringLiteral(""));
        pushButton_9_plus_12->setAutoDefault(true);
        pushButton_20_plus_23_21_24 = new QPushButton(centralWidget);
        pushButton_20_plus_23_21_24->setObjectName(QStringLiteral("pushButton_20_plus_23_21_24"));
        pushButton_20_plus_23_21_24->setGeometry(QRect(561, 173, 12, 12));
        pushButton_20_plus_23_21_24->setStyleSheet(QStringLiteral(""));
        pushButton_20_plus_23_21_24->setAutoDefault(true);
        pushButton_14_plus_15 = new QPushButton(centralWidget);
        pushButton_14_plus_15->setObjectName(QStringLiteral("pushButton_14_plus_15"));
        pushButton_14_plus_15->setGeometry(QRect(369, 174, 61, 8));
        pushButton_14_plus_15->setStyleSheet(QStringLiteral(""));
        pushButton_14_plus_15->setAutoDefault(true);
        pushButton_14_plus_17_15_18 = new QPushButton(centralWidget);
        pushButton_14_plus_17_15_18->setObjectName(QStringLiteral("pushButton_14_plus_17_15_18"));
        pushButton_14_plus_17_15_18->setGeometry(QRect(426, 172, 12, 12));
        pushButton_14_plus_17_15_18->setStyleSheet(QStringLiteral(""));
        pushButton_14_plus_17_15_18->setAutoDefault(true);
        pushButton_11_plus_14_12_15 = new QPushButton(centralWidget);
        pushButton_11_plus_14_12_15->setObjectName(QStringLiteral("pushButton_11_plus_14_12_15"));
        pushButton_11_plus_14_12_15->setGeometry(QRect(360, 173, 12, 12));
        pushButton_11_plus_14_12_15->setStyleSheet(QStringLiteral(""));
        pushButton_11_plus_14_12_15->setAutoDefault(true);
        pushButton_11_plus_12 = new QPushButton(centralWidget);
        pushButton_11_plus_12->setObjectName(QStringLiteral("pushButton_11_plus_12"));
        pushButton_11_plus_12->setGeometry(QRect(301, 175, 61, 8));
        pushButton_11_plus_12->setStyleSheet(QStringLiteral(""));
        pushButton_11_plus_12->setAutoDefault(true);
        pushButton_8_plus_11_9_12 = new QPushButton(centralWidget);
        pushButton_8_plus_11_9_12->setObjectName(QStringLiteral("pushButton_8_plus_11_9_12"));
        pushButton_8_plus_11_9_12->setGeometry(QRect(292, 173, 12, 12));
        pushButton_8_plus_11_9_12->setStyleSheet(QStringLiteral(""));
        pushButton_8_plus_11_9_12->setAutoDefault(true);
        pushButton_8_plus_9 = new QPushButton(centralWidget);
        pushButton_8_plus_9->setObjectName(QStringLiteral("pushButton_8_plus_9"));
        pushButton_8_plus_9->setGeometry(QRect(234, 175, 61, 8));
        pushButton_8_plus_9->setStyleSheet(QStringLiteral(""));
        pushButton_8_plus_9->setAutoDefault(true);
        pushButton_10_plus_13_11_14 = new QPushButton(centralWidget);
        pushButton_10_plus_13_11_14->setObjectName(QStringLiteral("pushButton_10_plus_13_11_14"));
        pushButton_10_plus_13_11_14->setGeometry(QRect(359, 240, 12, 12));
        pushButton_10_plus_13_11_14->setStyleSheet(QStringLiteral(""));
        pushButton_10_plus_13_11_14->setAutoDefault(true);
        pushButton_10_plus_11 = new QPushButton(centralWidget);
        pushButton_10_plus_11->setObjectName(QStringLiteral("pushButton_10_plus_11"));
        pushButton_10_plus_11->setGeometry(QRect(301, 242, 61, 8));
        pushButton_10_plus_11->setStyleSheet(QStringLiteral(""));
        pushButton_10_plus_11->setAutoDefault(true);
        pushButton_13_plus_14 = new QPushButton(centralWidget);
        pushButton_13_plus_14->setObjectName(QStringLiteral("pushButton_13_plus_14"));
        pushButton_13_plus_14->setGeometry(QRect(368, 241, 61, 8));
        pushButton_13_plus_14->setStyleSheet(QStringLiteral(""));
        pushButton_13_plus_14->setAutoDefault(true);
        pushButton_17_plus_18 = new QPushButton(centralWidget);
        pushButton_17_plus_18->setObjectName(QStringLiteral("pushButton_17_plus_18"));
        pushButton_17_plus_18->setGeometry(QRect(435, 174, 61, 8));
        pushButton_17_plus_18->setStyleSheet(QStringLiteral(""));
        pushButton_17_plus_18->setAutoDefault(true);
        pushButton_16_plus_17 = new QPushButton(centralWidget);
        pushButton_16_plus_17->setObjectName(QStringLiteral("pushButton_16_plus_17"));
        pushButton_16_plus_17->setGeometry(QRect(435, 241, 61, 8));
        pushButton_16_plus_17->setStyleSheet(QStringLiteral(""));
        pushButton_16_plus_17->setAutoDefault(true);
        pushButton_20_plus_21 = new QPushButton(centralWidget);
        pushButton_20_plus_21->setObjectName(QStringLiteral("pushButton_20_plus_21"));
        pushButton_20_plus_21->setGeometry(QRect(503, 174, 61, 8));
        pushButton_20_plus_21->setStyleSheet(QStringLiteral(""));
        pushButton_20_plus_21->setAutoDefault(true);
        pushButton_23_plus_24 = new QPushButton(centralWidget);
        pushButton_23_plus_24->setObjectName(QStringLiteral("pushButton_23_plus_24"));
        pushButton_23_plus_24->setGeometry(QRect(570, 174, 61, 8));
        pushButton_23_plus_24->setStyleSheet(QStringLiteral(""));
        pushButton_23_plus_24->setAutoDefault(true);
        pushButton_19_plus_20 = new QPushButton(centralWidget);
        pushButton_19_plus_20->setObjectName(QStringLiteral("pushButton_19_plus_20"));
        pushButton_19_plus_20->setGeometry(QRect(503, 241, 61, 8));
        pushButton_19_plus_20->setStyleSheet(QStringLiteral(""));
        pushButton_19_plus_20->setAutoDefault(true);
        pushButton_22_plus_23 = new QPushButton(centralWidget);
        pushButton_22_plus_23->setObjectName(QStringLiteral("pushButton_22_plus_23"));
        pushButton_22_plus_23->setGeometry(QRect(570, 241, 61, 8));
        pushButton_22_plus_23->setStyleSheet(QStringLiteral(""));
        pushButton_22_plus_23->setAutoDefault(true);
        pushButton_26_plus_27 = new QPushButton(centralWidget);
        pushButton_26_plus_27->setObjectName(QStringLiteral("pushButton_26_plus_27"));
        pushButton_26_plus_27->setGeometry(QRect(637, 174, 61, 8));
        pushButton_26_plus_27->setStyleSheet(QStringLiteral(""));
        pushButton_26_plus_27->setAutoDefault(true);
        pushButton_25_plus_26 = new QPushButton(centralWidget);
        pushButton_25_plus_26->setObjectName(QStringLiteral("pushButton_25_plus_26"));
        pushButton_25_plus_26->setGeometry(QRect(637, 241, 61, 8));
        pushButton_25_plus_26->setStyleSheet(QStringLiteral(""));
        pushButton_25_plus_26->setAutoDefault(true);
        pushButton_29_plus_30 = new QPushButton(centralWidget);
        pushButton_29_plus_30->setObjectName(QStringLiteral("pushButton_29_plus_30"));
        pushButton_29_plus_30->setGeometry(QRect(704, 174, 61, 8));
        pushButton_29_plus_30->setStyleSheet(QStringLiteral(""));
        pushButton_29_plus_30->setAutoDefault(true);
        pushButton_28_plus_29 = new QPushButton(centralWidget);
        pushButton_28_plus_29->setObjectName(QStringLiteral("pushButton_28_plus_29"));
        pushButton_28_plus_29->setGeometry(QRect(704, 241, 61, 8));
        pushButton_28_plus_29->setStyleSheet(QStringLiteral(""));
        pushButton_28_plus_29->setAutoDefault(true);
        pushButton_35_plus_36 = new QPushButton(centralWidget);
        pushButton_35_plus_36->setObjectName(QStringLiteral("pushButton_35_plus_36"));
        pushButton_35_plus_36->setGeometry(QRect(838, 174, 61, 8));
        pushButton_35_plus_36->setStyleSheet(QStringLiteral(""));
        pushButton_35_plus_36->setAutoDefault(true);
        pushButton_34_plus_35 = new QPushButton(centralWidget);
        pushButton_34_plus_35->setObjectName(QStringLiteral("pushButton_34_plus_35"));
        pushButton_34_plus_35->setGeometry(QRect(838, 241, 61, 8));
        pushButton_34_plus_35->setStyleSheet(QStringLiteral(""));
        pushButton_34_plus_35->setAutoDefault(true);
        pushButton_31_plus_32 = new QPushButton(centralWidget);
        pushButton_31_plus_32->setObjectName(QStringLiteral("pushButton_31_plus_32"));
        pushButton_31_plus_32->setGeometry(QRect(771, 241, 61, 8));
        pushButton_31_plus_32->setStyleSheet(QStringLiteral(""));
        pushButton_31_plus_32->setAutoDefault(true);
        pushButton_32_plus_33 = new QPushButton(centralWidget);
        pushButton_32_plus_33->setObjectName(QStringLiteral("pushButton_32_plus_33"));
        pushButton_32_plus_33->setGeometry(QRect(771, 174, 61, 8));
        pushButton_32_plus_33->setStyleSheet(QStringLiteral(""));
        pushButton_32_plus_33->setAutoDefault(true);
        Bet_button1 = new QPushButton(centralWidget);
        Bet_button1->setObjectName(QStringLiteral("Bet_button1"));
        Bet_button1->setGeometry(QRect(10, 450, 41, 41));
        QIcon icon;
        icon.addFile(QStringLiteral(":/imgs/Chip_5.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button1->setIcon(icon);
        Bet_button1->setIconSize(QSize(40, 40));
        Bet_button1->setAutoDefault(true);
        Bet_button2 = new QPushButton(centralWidget);
        Bet_button2->setObjectName(QStringLiteral("Bet_button2"));
        Bet_button2->setGeometry(QRect(70, 450, 41, 41));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/imgs/Chip_10.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button2->setIcon(icon1);
        Bet_button2->setIconSize(QSize(40, 40));
        Bet_button2->setAutoDefault(true);
        Bet_button3 = new QPushButton(centralWidget);
        Bet_button3->setObjectName(QStringLiteral("Bet_button3"));
        Bet_button3->setGeometry(QRect(130, 450, 41, 41));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/imgs/Chip_50.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button3->setIcon(icon2);
        Bet_button3->setIconSize(QSize(40, 40));
        Bet_button3->setAutoDefault(true);
        Bet_button4 = new QPushButton(centralWidget);
        Bet_button4->setObjectName(QStringLiteral("Bet_button4"));
        Bet_button4->setGeometry(QRect(190, 450, 41, 41));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/imgs/Chip_100.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button4->setIcon(icon3);
        Bet_button4->setIconSize(QSize(40, 40));
        Bet_button4->setAutoDefault(true);
        Clear_Button = new QPushButton(centralWidget);
        Clear_Button->setObjectName(QStringLiteral("Clear_Button"));
        Clear_Button->setGeometry(QRect(710, 460, 75, 23));
        Clear_Button->setAutoDefault(true);
        label_gif = new QLabel(centralWidget);
        label_gif->setObjectName(QStringLiteral("label_gif"));
        label_gif->setGeometry(QRect(445, 510, 111, 91));
        label_gif->setMidLineWidth(0);
        label_gif->setPixmap(QPixmap(QString::fromUtf8(":/imgs/roulette3.gif")));
        Bet_button5 = new QPushButton(centralWidget);
        Bet_button5->setObjectName(QStringLiteral("Bet_button5"));
        Bet_button5->setGeometry(QRect(250, 450, 41, 41));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/imgs/Chip_500.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button5->setIcon(icon4);
        Bet_button5->setIconSize(QSize(40, 40));
        Bet_button5->setAutoDefault(true);
        Bet_button6 = new QPushButton(centralWidget);
        Bet_button6->setObjectName(QStringLiteral("Bet_button6"));
        Bet_button6->setGeometry(QRect(310, 450, 41, 41));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/imgs/Chip_1000.gif"), QSize(), QIcon::Normal, QIcon::Off);
        Bet_button6->setIcon(icon5);
        Bet_button6->setIconSize(QSize(40, 40));
        Bet_button6->setAutoDefault(true);
        pushButton_street_6 = new QPushButton(centralWidget);
        pushButton_street_6->setObjectName(QStringLiteral("pushButton_street_6"));
        pushButton_street_6->setGeometry(QRect(434, 309, 61, 8));
        pushButton_street_6->setStyleSheet(QStringLiteral(""));
        pushButton_street_6->setAutoDefault(true);
        pushButton_street_10 = new QPushButton(centralWidget);
        pushButton_street_10->setObjectName(QStringLiteral("pushButton_street_10"));
        pushButton_street_10->setGeometry(QRect(703, 309, 61, 8));
        pushButton_street_10->setStyleSheet(QStringLiteral(""));
        pushButton_street_10->setAutoDefault(true);
        pushButton_line_2 = new QPushButton(centralWidget);
        pushButton_line_2->setObjectName(QStringLiteral("pushButton_line_2"));
        pushButton_line_2->setGeometry(QRect(224, 308, 12, 12));
        pushButton_line_2->setStyleSheet(QStringLiteral(""));
        pushButton_line_2->setAutoDefault(true);
        pushButton_street_3 = new QPushButton(centralWidget);
        pushButton_street_3->setObjectName(QStringLiteral("pushButton_street_3"));
        pushButton_street_3->setGeometry(QRect(233, 310, 61, 8));
        pushButton_street_3->setStyleSheet(QStringLiteral(""));
        pushButton_street_3->setAutoDefault(true);
        pushButton_line_3 = new QPushButton(centralWidget);
        pushButton_line_3->setObjectName(QStringLiteral("pushButton_line_3"));
        pushButton_line_3->setGeometry(QRect(291, 308, 12, 12));
        pushButton_line_3->setStyleSheet(QStringLiteral(""));
        pushButton_line_3->setAutoDefault(true);
        pushButton_line_5 = new QPushButton(centralWidget);
        pushButton_line_5->setObjectName(QStringLiteral("pushButton_line_5"));
        pushButton_line_5->setGeometry(QRect(425, 307, 12, 12));
        pushButton_line_5->setStyleSheet(QStringLiteral(""));
        pushButton_line_5->setAutoDefault(true);
        pushButton_line_11 = new QPushButton(centralWidget);
        pushButton_line_11->setObjectName(QStringLiteral("pushButton_line_11"));
        pushButton_line_11->setGeometry(QRect(828, 307, 12, 12));
        pushButton_line_11->setStyleSheet(QStringLiteral(""));
        pushButton_line_11->setAutoDefault(true);
        pushButton_street_2 = new QPushButton(centralWidget);
        pushButton_street_2->setObjectName(QStringLiteral("pushButton_street_2"));
        pushButton_street_2->setGeometry(QRect(166, 311, 61, 8));
        pushButton_street_2->setStyleSheet(QStringLiteral(""));
        pushButton_street_2->setAutoDefault(true);
        pushButton_line_6 = new QPushButton(centralWidget);
        pushButton_line_6->setObjectName(QStringLiteral("pushButton_line_6"));
        pushButton_line_6->setGeometry(QRect(492, 307, 12, 12));
        pushButton_line_6->setStyleSheet(QStringLiteral(""));
        pushButton_line_6->setAutoDefault(true);
        pushButton_street_5 = new QPushButton(centralWidget);
        pushButton_street_5->setObjectName(QStringLiteral("pushButton_street_5"));
        pushButton_street_5->setGeometry(QRect(367, 309, 61, 8));
        pushButton_street_5->setStyleSheet(QStringLiteral(""));
        pushButton_street_5->setAutoDefault(true);
        pushButton_street_9 = new QPushButton(centralWidget);
        pushButton_street_9->setObjectName(QStringLiteral("pushButton_street_9"));
        pushButton_street_9->setGeometry(QRect(636, 309, 61, 8));
        pushButton_street_9->setStyleSheet(QStringLiteral(""));
        pushButton_street_9->setAutoDefault(true);
        pushButton_line_8 = new QPushButton(centralWidget);
        pushButton_line_8->setObjectName(QStringLiteral("pushButton_line_8"));
        pushButton_line_8->setGeometry(QRect(627, 307, 12, 12));
        pushButton_line_8->setStyleSheet(QStringLiteral(""));
        pushButton_line_8->setAutoDefault(true);
        pushButton_line_4 = new QPushButton(centralWidget);
        pushButton_line_4->setObjectName(QStringLiteral("pushButton_line_4"));
        pushButton_line_4->setGeometry(QRect(358, 308, 12, 12));
        pushButton_line_4->setStyleSheet(QStringLiteral(""));
        pushButton_line_4->setAutoDefault(true);
        pushButton_street_1 = new QPushButton(centralWidget);
        pushButton_street_1->setObjectName(QStringLiteral("pushButton_street_1"));
        pushButton_street_1->setGeometry(QRect(99, 311, 61, 8));
        pushButton_street_1->setStyleSheet(QStringLiteral(""));
        pushButton_street_1->setAutoDefault(true);
        pushButton_line_7 = new QPushButton(centralWidget);
        pushButton_line_7->setObjectName(QStringLiteral("pushButton_line_7"));
        pushButton_line_7->setGeometry(QRect(560, 307, 12, 12));
        pushButton_line_7->setStyleSheet(QStringLiteral(""));
        pushButton_line_7->setAutoDefault(true);
        pushButton_line_10 = new QPushButton(centralWidget);
        pushButton_line_10->setObjectName(QStringLiteral("pushButton_line_10"));
        pushButton_line_10->setGeometry(QRect(761, 307, 12, 12));
        pushButton_line_10->setStyleSheet(QStringLiteral(""));
        pushButton_line_10->setAutoDefault(true);
        pushButton_line_9 = new QPushButton(centralWidget);
        pushButton_line_9->setObjectName(QStringLiteral("pushButton_line_9"));
        pushButton_line_9->setGeometry(QRect(694, 307, 12, 12));
        pushButton_line_9->setStyleSheet(QStringLiteral(""));
        pushButton_line_9->setAutoDefault(true);
        pushButton_line_1 = new QPushButton(centralWidget);
        pushButton_line_1->setObjectName(QStringLiteral("pushButton_line_1"));
        pushButton_line_1->setGeometry(QRect(157, 308, 12, 12));
        pushButton_line_1->setStyleSheet(QStringLiteral(""));
        pushButton_line_1->setAutoDefault(true);
        pushButton_street_7 = new QPushButton(centralWidget);
        pushButton_street_7->setObjectName(QStringLiteral("pushButton_street_7"));
        pushButton_street_7->setGeometry(QRect(502, 309, 61, 8));
        pushButton_street_7->setStyleSheet(QStringLiteral(""));
        pushButton_street_7->setAutoDefault(true);
        pushButton_street_8 = new QPushButton(centralWidget);
        pushButton_street_8->setObjectName(QStringLiteral("pushButton_street_8"));
        pushButton_street_8->setGeometry(QRect(569, 309, 61, 8));
        pushButton_street_8->setStyleSheet(QStringLiteral(""));
        pushButton_street_8->setAutoDefault(true);
        pushButton_street_12 = new QPushButton(centralWidget);
        pushButton_street_12->setObjectName(QStringLiteral("pushButton_street_12"));
        pushButton_street_12->setGeometry(QRect(837, 309, 61, 8));
        pushButton_street_12->setStyleSheet(QStringLiteral(""));
        pushButton_street_12->setAutoDefault(true);
        pushButton_street_11 = new QPushButton(centralWidget);
        pushButton_street_11->setObjectName(QStringLiteral("pushButton_street_11"));
        pushButton_street_11->setGeometry(QRect(770, 309, 61, 8));
        pushButton_street_11->setStyleSheet(QStringLiteral(""));
        pushButton_street_11->setAutoDefault(true);
        pushButton_street_4 = new QPushButton(centralWidget);
        pushButton_street_4->setObjectName(QStringLiteral("pushButton_street_4"));
        pushButton_street_4->setGeometry(QRect(300, 310, 61, 8));
        pushButton_street_4->setStyleSheet(QStringLiteral(""));
        pushButton_street_4->setAutoDefault(true);
        pushButton_3rd_row = new QPushButton(centralWidget);
        pushButton_3rd_row->setObjectName(QStringLiteral("pushButton_3rd_row"));
        pushButton_3rd_row->setGeometry(QRect(950, 110, 8, 61));
        pushButton_3rd_row->setStyleSheet(QStringLiteral(""));
        pushButton_3rd_row->setAutoDefault(true);
        pushButton_2nd_row = new QPushButton(centralWidget);
        pushButton_2nd_row->setObjectName(QStringLiteral("pushButton_2nd_row"));
        pushButton_2nd_row->setGeometry(QRect(950, 180, 8, 61));
        pushButton_2nd_row->setStyleSheet(QStringLiteral(""));
        pushButton_2nd_row->setAutoDefault(true);
        pushButton_1st_row = new QPushButton(centralWidget);
        pushButton_1st_row->setObjectName(QStringLiteral("pushButton_1st_row"));
        pushButton_1st_row->setGeometry(QRect(950, 250, 8, 61));
        pushButton_1st_row->setStyleSheet(QStringLiteral(""));
        pushButton_1st_row->setAutoDefault(true);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 520, 91, 21));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 550, 91, 21));
        nameShowcase = new QLabel(centralWidget);
        nameShowcase->setObjectName(QStringLiteral("nameShowcase"));
        nameShowcase->setGeometry(QRect(100, 520, 91, 21));
        creditsShowcase = new QLabel(centralWidget);
        creditsShowcase->setObjectName(QStringLiteral("creditsShowcase"));
        creditsShowcase->setGeometry(QRect(100, 550, 91, 21));
        MainWindow->setCentralWidget(centralWidget);
        pushButton_1->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        pushButton_6->raise();
        pushButton_spin->raise();
        pushButton_10->raise();
        pushButton_9->raise();
        pushButton_11->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        pushButton_12->raise();
        pushButton_16->raise();
        pushButton_15->raise();
        pushButton_17->raise();
        pushButton_13->raise();
        pushButton_14->raise();
        pushButton_18->raise();
        pushButton_22->raise();
        pushButton_21->raise();
        pushButton_23->raise();
        pushButton_19->raise();
        pushButton_20->raise();
        pushButton_24->raise();
        pushButton_28->raise();
        pushButton_27->raise();
        pushButton_29->raise();
        pushButton_25->raise();
        pushButton_26->raise();
        pushButton_30->raise();
        pushButton_34->raise();
        pushButton_33->raise();
        pushButton_35->raise();
        pushButton_31->raise();
        pushButton_32->raise();
        pushButton_36->raise();
        pushButton_0->raise();
        pushButton_1st->raise();
        pushButton_2nd->raise();
        pushButton_3rd->raise();
        pushButton_1_18->raise();
        pushButton_even->raise();
        redButton_red->raise();
        pushButton_black->raise();
        pushButton_odd->raise();
        pushButton_19_36->raise();
        pushButton_2to1_3->raise();
        pushButton_2to1_2->raise();
        pushButton_2to1_1->raise();
        pushButton_1_plus_4->raise();
        pushButton_2_plus_5->raise();
        pushButton_1_plus_2->raise();
        pushButton_4_plus_5->raise();
        pushButton_3_plus_6->raise();
        pushButton_2_plus_3->raise();
        pushButton_5_plus_6->raise();
        pushButton_6_plus_9->raise();
        pushButton_4_plus_7->raise();
        pushButton_5_plus_8->raise();
        pushButton_7_plus_8->raise();
        pushButton_19_plus_22->raise();
        pushButton_20_plus_23->raise();
        pushButton_13_plus_16->raise();
        pushButton_18_plus_21->raise();
        pushButton_21_plus_24->raise();
        pushButton_14_plus_17->raise();
        pushButton_29_plus_32->raise();
        pushButton_31_plus_34->raise();
        pushButton_23_plus_26->raise();
        pushButton_28_plus_31->raise();
        pushButton_32_plus_35->raise();
        pushButton_30_plus_33->raise();
        pushButton_27_plus_30->raise();
        pushButton_33_plus_36->raise();
        pushButton_25_plus_28->raise();
        pushButton_22_plus_25->raise();
        pushButton_26_plus_29->raise();
        pushButton_24_plus_27->raise();
        pushButton_16_plus_19->raise();
        pushButton_17_plus_20->raise();
        pushButton_15_plus_18->raise();
        pushButton_7_plus_10->raise();
        pushButton_10_plus_13->raise();
        pushButton_8_plus_11->raise();
        pushButton_11_plus_14->raise();
        pushButton_12_plus_15->raise();
        pushButton_9_plus_12->raise();
        pushButton_14_plus_15->raise();
        pushButton_11_plus_12->raise();
        pushButton_8_plus_9->raise();
        pushButton_10_plus_11->raise();
        pushButton_13_plus_14->raise();
        pushButton_17_plus_18->raise();
        pushButton_16_plus_17->raise();
        pushButton_20_plus_21->raise();
        pushButton_23_plus_24->raise();
        pushButton_19_plus_20->raise();
        pushButton_22_plus_23->raise();
        pushButton_26_plus_27->raise();
        pushButton_25_plus_26->raise();
        pushButton_29_plus_30->raise();
        pushButton_28_plus_29->raise();
        pushButton_35_plus_36->raise();
        pushButton_34_plus_35->raise();
        pushButton_31_plus_32->raise();
        pushButton_32_plus_33->raise();
        Bet_button1->raise();
        Bet_button2->raise();
        Bet_button3->raise();
        Bet_button4->raise();
        Clear_Button->raise();
        label_gif->raise();
        Bet_button5->raise();
        Bet_button6->raise();
        pushButton_street_6->raise();
        pushButton_street_10->raise();
        pushButton_street_3->raise();
        pushButton_street_2->raise();
        pushButton_street_5->raise();
        pushButton_street_9->raise();
        pushButton_street_1->raise();
        pushButton_street_7->raise();
        pushButton_street_8->raise();
        pushButton_street_12->raise();
        pushButton_street_4->raise();
        pushButton_3rd_row->raise();
        pushButton_2nd_row->raise();
        pushButton_1st_row->raise();
        label->raise();
        label_2->raise();
        nameShowcase->raise();
        creditsShowcase->raise();
        pushButton_street_11->raise();
        pushButton_1_plus_4_2_5->raise();
        pushButton_2_plus_5_3_6->raise();
        pushButton_5_plus_8_6_9->raise();
        pushButton_4_plus_7_5_8->raise();
        pushButton_7_plus_10_8_11->raise();
        pushButton_8_plus_11_9_12->raise();
        pushButton_11_plus_14_12_15->raise();
        pushButton_10_plus_13_11_14->raise();
        pushButton_13_plus_16_14_17->raise();
        pushButton_14_plus_17_15_18->raise();
        pushButton_17_plus_20_18_21->raise();
        pushButton_16_plus_19_17_20->raise();
        pushButton_19_plus_22_20_23->raise();
        pushButton_20_plus_23_21_24->raise();
        pushButton_23_plus_26_24_27->raise();
        pushButton_22_plus_25_23_26->raise();
        pushButton_25_plus_28_26_29->raise();
        pushButton_26_plus_29_27_30->raise();
        pushButton_29_plus_32_30_33->raise();
        pushButton_28_plus_31_29_32->raise();
        pushButton_31_plus_34_32_35->raise();
        pushButton_32_plus_35_33_36->raise();
        pushButton_line_11->raise();
        pushButton_line_10->raise();
        pushButton_line_9->raise();
        pushButton_line_8->raise();
        pushButton_line_7->raise();
        pushButton_line_6->raise();
        pushButton_line_5->raise();
        pushButton_line_4->raise();
        pushButton_line_3->raise();
        pushButton_line_2->raise();
        pushButton_line_1->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1108, 21));
        menuRoullet = new QMenu(menuBar);
        menuRoullet->setObjectName(QStringLiteral("menuRoullet"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuRoullet->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        pushButton_1->setText(QApplication::translate("MainWindow", "1", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "2", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "3", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "4", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "5", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "6", 0));
        pushButton_spin->setText(QApplication::translate("MainWindow", "Spin", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "10", 0));
        pushButton_9->setText(QApplication::translate("MainWindow", "9", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "11", 0));
        pushButton_7->setText(QApplication::translate("MainWindow", "7", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "8", 0));
        pushButton_12->setText(QApplication::translate("MainWindow", "12", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "16", 0));
        pushButton_15->setText(QApplication::translate("MainWindow", "15", 0));
        pushButton_17->setText(QApplication::translate("MainWindow", "17", 0));
        pushButton_13->setText(QApplication::translate("MainWindow", "13", 0));
        pushButton_14->setText(QApplication::translate("MainWindow", "14", 0));
        pushButton_18->setText(QApplication::translate("MainWindow", "18", 0));
        pushButton_22->setText(QApplication::translate("MainWindow", "22", 0));
        pushButton_21->setText(QApplication::translate("MainWindow", "21", 0));
        pushButton_23->setText(QApplication::translate("MainWindow", "23", 0));
        pushButton_19->setText(QApplication::translate("MainWindow", "19", 0));
        pushButton_20->setText(QApplication::translate("MainWindow", "20", 0));
        pushButton_24->setText(QApplication::translate("MainWindow", "24", 0));
        pushButton_28->setText(QApplication::translate("MainWindow", "28", 0));
        pushButton_27->setText(QApplication::translate("MainWindow", "27", 0));
        pushButton_29->setText(QApplication::translate("MainWindow", "29", 0));
        pushButton_25->setText(QApplication::translate("MainWindow", "25", 0));
        pushButton_26->setText(QApplication::translate("MainWindow", "26", 0));
        pushButton_30->setText(QApplication::translate("MainWindow", "30", 0));
        pushButton_34->setText(QApplication::translate("MainWindow", "34", 0));
        pushButton_33->setText(QApplication::translate("MainWindow", "33", 0));
        pushButton_35->setText(QApplication::translate("MainWindow", "35", 0));
        pushButton_31->setText(QApplication::translate("MainWindow", "31", 0));
        pushButton_32->setText(QApplication::translate("MainWindow", "32", 0));
        pushButton_36->setText(QApplication::translate("MainWindow", "36", 0));
        pushButton_0->setText(QApplication::translate("MainWindow", "0", 0));
        pushButton_1st->setText(QApplication::translate("MainWindow", "1st 12", 0));
        pushButton_2nd->setText(QApplication::translate("MainWindow", "2nd 12", 0));
        pushButton_3rd->setText(QApplication::translate("MainWindow", "3rd 12", 0));
        pushButton_1_18->setText(QApplication::translate("MainWindow", "1-18", 0));
        pushButton_even->setText(QApplication::translate("MainWindow", "Even", 0));
        redButton_red->setText(QApplication::translate("MainWindow", "RED", 0));
        pushButton_black->setText(QApplication::translate("MainWindow", "BLACK", 0));
        pushButton_odd->setText(QApplication::translate("MainWindow", "Odd", 0));
        pushButton_19_36->setText(QApplication::translate("MainWindow", "19-36", 0));
        pushButton_2to1_3->setText(QApplication::translate("MainWindow", "2 to 1", 0));
        pushButton_2to1_2->setText(QApplication::translate("MainWindow", "2 to 1", 0));
        pushButton_2to1_1->setText(QApplication::translate("MainWindow", "2 to 1", 0));
        pushButton_1_plus_4->setText(QString());
        pushButton_2_plus_5->setText(QString());
        pushButton_1_plus_4_2_5->setText(QString());
        pushButton_2_plus_5_3_6->setText(QString());
        pushButton_7_plus_10_8_11->setText(QString());
        pushButton_26_plus_29_27_30->setText(QString());
        pushButton_1_plus_2->setText(QString());
        pushButton_4_plus_5->setText(QString());
        pushButton_3_plus_6->setText(QString());
        pushButton_2_plus_3->setText(QString());
        pushButton_5_plus_6->setText(QString());
        pushButton_6_plus_9->setText(QString());
        pushButton_5_plus_8_6_9->setText(QString());
        pushButton_4_plus_7_5_8->setText(QString());
        pushButton_4_plus_7->setText(QString());
        pushButton_5_plus_8->setText(QString());
        pushButton_7_plus_8->setText(QString());
        pushButton_23_plus_26_24_27->setText(QString());
        pushButton_19_plus_22->setText(QString());
        pushButton_20_plus_23->setText(QString());
        pushButton_13_plus_16->setText(QString());
        pushButton_32_plus_35_33_36->setText(QString());
        pushButton_22_plus_25_23_26->setText(QString());
        pushButton_18_plus_21->setText(QString());
        pushButton_21_plus_24->setText(QString());
        pushButton_14_plus_17->setText(QString());
        pushButton_29_plus_32_30_33->setText(QString());
        pushButton_29_plus_32->setText(QString());
        pushButton_31_plus_34->setText(QString());
        pushButton_23_plus_26->setText(QString());
        pushButton_28_plus_31->setText(QString());
        pushButton_32_plus_35->setText(QString());
        pushButton_30_plus_33->setText(QString());
        pushButton_27_plus_30->setText(QString());
        pushButton_33_plus_36->setText(QString());
        pushButton_25_plus_28->setText(QString());
        pushButton_25_plus_28_26_29->setText(QString());
        pushButton_22_plus_25->setText(QString());
        pushButton_26_plus_29->setText(QString());
        pushButton_24_plus_27->setText(QString());
        pushButton_31_plus_34_32_35->setText(QString());
        pushButton_19_plus_22_20_23->setText(QString());
        pushButton_16_plus_19->setText(QString());
        pushButton_17_plus_20->setText(QString());
        pushButton_15_plus_18->setText(QString());
        pushButton_28_plus_31_29_32->setText(QString());
        pushButton_16_plus_19_17_20->setText(QString());
        pushButton_7_plus_10->setText(QString());
        pushButton_10_plus_13->setText(QString());
        pushButton_8_plus_11->setText(QString());
        pushButton_17_plus_20_18_21->setText(QString());
        pushButton_13_plus_16_14_17->setText(QString());
        pushButton_11_plus_14->setText(QString());
        pushButton_12_plus_15->setText(QString());
        pushButton_9_plus_12->setText(QString());
        pushButton_20_plus_23_21_24->setText(QString());
        pushButton_14_plus_15->setText(QString());
        pushButton_14_plus_17_15_18->setText(QString());
        pushButton_11_plus_14_12_15->setText(QString());
        pushButton_11_plus_12->setText(QString());
        pushButton_8_plus_11_9_12->setText(QString());
        pushButton_8_plus_9->setText(QString());
        pushButton_10_plus_13_11_14->setText(QString());
        pushButton_10_plus_11->setText(QString());
        pushButton_13_plus_14->setText(QString());
        pushButton_17_plus_18->setText(QString());
        pushButton_16_plus_17->setText(QString());
        pushButton_20_plus_21->setText(QString());
        pushButton_23_plus_24->setText(QString());
        pushButton_19_plus_20->setText(QString());
        pushButton_22_plus_23->setText(QString());
        pushButton_26_plus_27->setText(QString());
        pushButton_25_plus_26->setText(QString());
        pushButton_29_plus_30->setText(QString());
        pushButton_28_plus_29->setText(QString());
        pushButton_35_plus_36->setText(QString());
        pushButton_34_plus_35->setText(QString());
        pushButton_31_plus_32->setText(QString());
        pushButton_32_plus_33->setText(QString());
        Bet_button1->setText(QString());
        Bet_button2->setText(QString());
        Bet_button3->setText(QString());
        Bet_button4->setText(QString());
        Clear_Button->setText(QApplication::translate("MainWindow", "Clear", 0));
        label_gif->setText(QString());
        Bet_button5->setText(QString());
        Bet_button6->setText(QString());
        pushButton_street_6->setText(QString());
        pushButton_street_10->setText(QString());
        pushButton_line_2->setText(QString());
        pushButton_street_3->setText(QString());
        pushButton_line_3->setText(QString());
        pushButton_line_5->setText(QString());
        pushButton_line_11->setText(QString());
        pushButton_street_2->setText(QString());
        pushButton_line_6->setText(QString());
        pushButton_street_5->setText(QString());
        pushButton_street_9->setText(QString());
        pushButton_line_8->setText(QString());
        pushButton_line_4->setText(QString());
        pushButton_street_1->setText(QString());
        pushButton_line_7->setText(QString());
        pushButton_line_10->setText(QString());
        pushButton_line_9->setText(QString());
        pushButton_line_1->setText(QString());
        pushButton_street_7->setText(QString());
        pushButton_street_8->setText(QString());
        pushButton_street_12->setText(QString());
        pushButton_street_11->setText(QString());
        pushButton_street_4->setText(QString());
        pushButton_3rd_row->setText(QString());
        pushButton_2nd_row->setText(QString());
        pushButton_1st_row->setText(QString());
        label->setText(QApplication::translate("MainWindow", "Name:", 0));
        label_2->setText(QApplication::translate("MainWindow", "Credits:", 0));
        nameShowcase->setText(QString());
        creditsShowcase->setText(QString());
        menuRoullet->setTitle(QApplication::translate("MainWindow", "Roullet", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
